### ISSUE TITLE
Add stdout tty detection

### ISSUE THREAD

**Issue by jhermann** [wolfg1969/oh-my-stars#9]
```console
$ python -c "import sys; print >>sys.stderr, sys.stdout.isatty()" >/dev/null
False
$ python -c "import sys; print >>sys.stderr, sys.stdout.isatty()"
True
```
Add the detection, and if not a tty…

* disable ANSI colors (also see `--color=auto` below)
* disable the pagination

In case you really want to catch colorized results., maybe a `--color` option.

    --color[=WHEN] colorize the output; WHEN can be 'always' (default if omitted), 'auto', or 'never'

Then you can also use `mystars foo | less -R` – the builtin pager is a bad idea anyway if you ask me, and violates the UNIX principle.

**Comment by wolfg1969** [comment]
Yes, you are right. I'll make the changes later. Thanks!
